#! /bin/bash
clear
echo +++++++++++++++++++++++++++++
cat customTestData.csv
echo +++++++++++++++++++++++++++++
cat pingData.txt
echo +++++++++++++++++++++++++++++
cat tracerouteData.txt
echo +++++++++++++++++++++++++++++
cat iperfDataClient.txt
echo +++++++++++++++++++++++++++++

