#! /bin/bash
clear
# ./testClient raspberrypi 26207
rm ../data/customTestData.csv
rm ../data/floodData.txt
rm ../data/iperfDataClient.txt
rm ../data/iperfDataServer.txt
rm ../data/pingData.txt
rm ../data/tracerouteData.txt
./testClient 192.168.1.164 26207
